name: Despliegue a Azure y ejecución de test

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
     # - run: npm install
     # - run: npm run build --if-present
     # - run: npm test
      - name: webfactory/ssh-agent     
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.AZURE_SECRET_KEY }}
<<<<<<< Updated upstream
          host: ${{ secrets.AZURE_HOST }} 
=======
<<<<<<< Updated upstream
          host: ${{ secrets.AZURE_HOST }} 
=======
          host: ${{ secrets.AZURE_HOST }}
>>>>>>> Stashed changes
>>>>>>> Stashed changes
          username: ${{ secrets.AZURE_USER }}

      - name: Desplegar a Azure
        run: |
          ssh -o StrictHostKeyChecking=no -t ${{ secrets.AZURE_USER }}@${{ secrets.AZURE_HOST }} "cd playbeat/Backend && git pull origin main && 
          docker stop playbeat_container && docker rm playbeat_container && docker rmi playbeat && docker build -t playbeat:latest . && 
          docker run -d --name playbeat_container -p 3000:3000 playbeat:latest"
        # Tengo que guardarme el .env, ya que me lo van a eliminar
        # Una opción mas rapida puede ser instalar git en el contenedo, conectarme y realizar el git pull origin main y el npm stop, 
        # npm install y npm start, de esta forma no tardaria tanto en tener que crear un nuevo contenedor.