name: Despliegue a Azure y ejecución de test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PRIVATE_KEY: ${{ secrets.AZURE }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Crear directorio .ssh
        run: mkdir -p ~/.ssh

      - name: Imprimir Contenido de la Clave Privada
        run: echo "$PRIVATE_KEY"

      - name: Configurar Permisos de la Clave Privada
        run: echo "$PRIVATE_KEY" > ~/.ssh/private_key.pem && chmod 600 ~/.ssh/private_key.pem

      - name: Agregar clave del host a known_hosts
        run: ssh-keyscan -t rsa playbeat.uksouth.cloudapp.azure.com >> ~/.ssh/known_hosts

      - name: Desplegar a Azure
        run: |
          ssh -i ~/.ssh/private_key.pem azureuser@playbeat.uksouth.cloudapp.azure.com "cd playbeat/Backend && git pull origin main && npm install && npm restart"
