name: Despliegue a Azure y ejecución de test

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PRIVATE_KEY: ${{ secrets.AZURE_SECRET_KEY }}

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
     # - run: npm install
     # - run: npm run build --if-present
     # - run: npm test
      - name: webfactory/ssh-agent     
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.AZURE_SECRET_KEY }}
          host: 'playbeat.uksouth.cloudapp.azure.com'
          username: 'azureuser'

      - name: Desplegar a Azure
        run: |
          ssh -o StrictHostKeyChecking=no -t azureuser@playbeat.uksouth.cloudapp.azure.com "cd playbeat/Backend && git pull origin main && docker stop playbeat_container && 
          docker build -t playbeat:latest . && docker run -d --name playbeat_container -p 3000:3000 playbeat:latest"