name: Despliegue a Azure y ejecución de test

on:
  pull_request: 
    branches:
      - main
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    #steps:
    #- name: Checkout código
    #  uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    #- name: Instalar dependencias
    #  run: npm install

    #- name: Construir la aplicación
    #  run: npm start  # Asegúrate de ajustar esto según tus necesidades

    - name: Desplegar a Azure
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        ssh -i private_key.pem azureuser@<DIRECCION_IP_AZURE> "cd /playbeat && git pull origin main && npm install && npm restart"
      env:
        PRIVATE_KEY: ${{ secrets.azure }}
