name: Despliegue a Azure y ejecución de test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PRIVATE_KEY: ${{ secrets.AZURE }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: executing remote ssh commands using key
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          ssh -i private_key.pem ${{ secrets.USERNAME }}@${{ secrets.HOST }} "cd playbeat/Backend && git pull origin main && npm install && npm restart"
