
name: Despliegue a Azure y ejecución de testss

on:
  push: 
    branches:
      - main

  pull_request: 
    branches:
      - main

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    permissions:
          contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        run: npm test

      - name: Set commit status
        if: always()
        uses: EndBug/add-and-commit@v7
        with:
          add: "."
          message: "Tests passed"
          author_name: "Garicore01"
          author_email: "848905@unizar.es"
          author_date: "$(date -u +%Y-%m-%dT%H:%M:%SZ)"

  deploy_to_azure:
    needs: test_and_deploy
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.test_and_deploy.result == 'success' }}
    steps:
      - name: webfactory/ssh-agent     
        uses: webfactory/ssh-agent@v0.9.0 
        with:
          ssh-private-key: ${{ secrets.AZURE_SECRET_KEY }}
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build Docker image
        run: docker build --tag playbeat .
      
      - name: Save Docker image as tar
        run: docker save playbeat -o playbeat.tar

      - name: Dar permisos de lectura
        run: chmod +r playbeat.tar
      
      - name: List files after build
        run: ls -la
      
      - name: Copy Docker image to Azure VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SECRET_KEY }}
          source: "playbeat.tar"
          target: "/home${{ secrets.RUTA_PLAYBEAT }}playbeat.tar"

      - name: Desplegar a Azure
        run: |
          ssh -o StrictHostKeyChecking=no -t ${{ secrets.AZURE_USER }}@${{ secrets.AZURE_HOST }} "cd playbeat/Backend &&  docker load -i playbeat.tar &&
          docker stop playbeat_container && docker rm playbeat_container && docker rmi playbeat && 
          docker run -v audios_playbeat:/app/audios -d --name playbeat_container -p 3000:3000 -p 3001:3001 playbeat:latest"


